### ISSUE TITLE
Add a way to implement the reaper pattern

### ISSUE THREAD

**Issue by 422404** [422404/ActorLang#33]
Add a way to implement the Reaper Pattern without introducing complex functionalities to the language.
It could be done by adding these functionalities to the system:
- [ ] [A `shutdown` statement which shutdown a running instance](https://github.com/422404/ActorLang/issues/36)
- [ ] [A `PoisonPill` literal value which kills an actor receiving it](https://github.com/422404/ActorLang/issues/35)
- [ ] [Sets](https://github.com/422404/ActorLang/issues/34)
- [ ] [A way to indicate that an actor must receive messages about other actors death](https://github.com/422404/ActorLang/issues/37)

Example:
```
Reaper (Actors) [dead] = {
  if (setContains(Actors, dead)) {
    setRemove(Actors, dead)
  }
  if (setEmpty(Actors)) {
    shutdown
  }
};

MyActor () ["display", str] = {
  display str;
  send [PoisonPill] to self
};

MyActor () ["start"] = {
  send ["display", "Hello, world!"] to self
};

actor = create MyActor ();
trackedActors = setNew();
setAdd(trackedActors, actor);
@system.events.reaper = create Reaper (trackedActors);

send ["start"] to actor
```
